
databases:
  - name: nexon-mongo
    plan: free

services:
  - type: web
    name: nexon
    runtime: node
    region: oregon =
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18 
      - key: JWT_KEY
        sync: false
      - key: EXPRESS_SESSION_SECRET
        sync: false
      - key: MONGODB_URI
        fromDatabase:
          name: nexon-mongo
          property: connectionString
      - key: PHONEPE_MERCHANT_ID
        sync: false
      - key: PHONEPE_SALT_KEY
        sync: false
      - key: PHONEPE_SALT_INDEX
        sync: false
      - key: APP_BE_URL
        sync: false
    env: node
    startCommand: node app.js 
    autoDeploy: true
